### ISSUE TITLE
App crashes beyond 'Stops' Screen

### ISSUE THREAD

**Issue by pccontroller** [nhandler/pebble-cumtd#6]
Running iOS 8 and Pebble v2.8 (problem occurred on 2.7 also).  The app will load the nearest stops, the correct ones too, but will crash after selecting a stop.  The window that appears just before the crash is blank white.

**Comment by edthedev** [comment]
Also happens running Android 4.4.2 with Pebble v.2.9.

**Comment by edthedev** [comment]
This problem is solved by the change provided by tmbg47 - Pull Request #7.

**Comment by parseccentric** [comment]
Works great for me.  Thanks!
